runtime:
  cache_dir: ./.cache/antora

site:
  title: Summit Connect Madrid 2024 - Event-Driven Ansible MicroLab
  url: http://localhost:3000/rhs-build-course/index.html
  start_page: microlab-aap-eda::index.adoc
content:
  sources:
    - url: ../
      branches: HEAD
      start_path: guide/documentation
asciidoc:
  attributes:
    title: Summit Connect Madrid 2024 - Event-Driven Ansible MicroLab
    page-pagination: true
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.14/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
